### ISSUE TITLE
struct.error when importing .w file with animated textures

### ISSUE THREAD

**Issue by Gotolei** [Yethiel/re-volt-addon#31]
Plugin version 18.6.19
Blender 2.79b

Feedback when trying to import market1.w:
```Traceback (most recent call last):
  File "/home/raster/.config/blender/2.79/scripts/addons/io_revolt/operators.py", line 95, in execute
    w_in.import_file(self.filepath, scene)
  File "/home/raster/.config/blender/2.79/scripts/addons/io_revolt/w_in.py", line 45, in import_file
    world = World(file)
  File "/home/raster/.config/blender/2.79/scripts/addons/io_revolt/rvstruct.py", line 57, in __init__
    self.read(file)
  File "/home/raster/.config/blender/2.79/scripts/addons/io_revolt/rvstruct.py", line 81, in read
    self.animations.append(TexAnimation(file))
  File "/home/raster/.config/blender/2.79/scripts/addons/io_revolt/rvstruct.py", line 667, in __init__
    self.read(file)
  File "/home/raster/.config/blender/2.79/scripts/addons/io_revolt/rvstruct.py", line 678, in read
    self.frames.append(Frame(file))
  File "/home/raster/.config/blender/2.79/scripts/addons/io_revolt/rvstruct.py", line 712, in __init__
    self.read(file)
  File "/home/raster/.config/blender/2.79/scripts/addons/io_revolt/rvstruct.py", line 724, in read
    self.delay = struct.unpack("<F", file.read(4))[0]
struct.error: bad char in struct format

location: <unknown location>:-1
```

Similar errors when trying to import other tracks with texanim, both stock (toylite, toy2, muse2 tested) and custom (donut3, lrc1r2, personal test track with otherwise very simple mesh).

**Comment by Yethiel** [comment]
fixed on the dev branch
